### ISSUE TITLE
When 1st request in Playlist class is made, it doesn't save a continuation key

### ISSUE THREAD

**Issue by Arctic4161** [alexmercerind/youtube-search-python#115]
This doesn't add any more videos to the list like it use to. List stays at 100 even though playlist has more than 100 videos.

```
while playlist.hasMoreVideos:
      playlist.getNextVideos()
```

There is no traceback or error message. Tested on multiple playlist with over 100 videos.

![Capture](https://user-images.githubusercontent.com/64910295/133627949-39fc7c31-0c90-40e0-9eef-d4054efec091.PNG)
![Capture1](https://user-images.githubusercontent.com/64910295/133627968-319371b5-7c86-46a9-9215-7a322aea5410.PNG)

**Comment by mytja** [comment]
I know this is an issue. It came with my PR to fix Playlist class. I will try to fix it as soon as possible. In the meantime can you share this playlist URL or any similar URLs that have more than 100 videos.
Thank you so much

**Comment by Arctic4161** [comment]
Here is the playlist as requested
https://www.youtube.com/watch?v=EPhWR4d3FJQ&list=PLI_TwOrHUsI8MQNW0BvBAwwHYKgyiiiDB

**Comment by mytja** [comment]
Thank you so much. I will have a look at it tomorrow

**Comment by mytja** [comment]
I have fixed this. Please install latest version using following command: `pip install git+https://github.com/alexmercerind/youtube-search-python`.
I was messing around quite a bit of time because of link format. Link should be as following:
https://www.youtube.com/playlist?list=PLI_TwOrHUsI8MQNW0BvBAwwHYKgyiiiDB
Not as:
https://www.youtube.com/watch?v=EPhWR4d3FJQ&list=PLI_TwOrHUsI8MQNW0BvBAwwHYKgyiiiDB
when you are passing it to a class.
I said this just for your knowledge (and also mine), because I messed around quite a bit. 😅 
Thank you so much. Please comment if error still occours to you

**Comment by deeznutterbutterz** [comment]
Issue still persists for me using the following link
https://www.youtube.com/playlist?list=PL5sMqiHHSWqeSHminsjrYY5rdGzVPNLEn
![image](https://user-images.githubusercontent.com/90943873/133868267-eaae89f1-68b9-45d0-96c0-4c3dd6abd5e9.png)
![image](https://user-images.githubusercontent.com/90943873/133868279-c4f5ecda-49ed-4383-a7a9-1dd5e0bfde2d.png)

**Comment by mytja** [comment]
Yupp. You have to install latest release from git using following command: `pip install git+https://github.com/alexmercerind/youtube-search-python`
Otherwise your example is working for me

**Comment by deeznutterbutterz** [comment]
??? Ok yeah my bad I did py filename.py instead of python3 filename.py and it works now sorry for the confusion haha
